# config/packages/monolog.yaml

monolog:
    channels:
        - deprecation

    # Configuration pour l'environnement de développement
    when@dev:
        monolog:
            handlers:
                main:
                    type: stream
                    path: "%kernel.logs_dir%/%kernel.environment%.log"
                    level: debug
                    channels: ["!event"]  # Exclure le canal 'event' pour éviter les logs trop détaillés
                console:
                    type: console
                    process_psr_3_messages: false
                    channels: ["!event", "!doctrine", "!console"]  # Exclure les canaux 'event', 'doctrine', et 'console'

    # Configuration pour l'environnement de test
    when@test:
        monolog:
            handlers:
                main:
                    type: fingers_crossed
                    action_level: error  # Se déclenche pour les erreurs
                    handler: nested
                    excluded_http_codes: [404, 405]
                    channels: ["!event"]  # Exclure le canal 'event'
                nested:
                    type: stream
                    path: "%kernel.logs_dir%/%kernel.environment%.log"
                    level: debug  # Conservez les logs de débogage pour les tests

    # Configuration pour l'environnement de production
    when@prod:
        monolog:
            handlers:
                main:
                    type: fingers_crossed
                    action_level: error  # Enregistre les erreurs critiques
                    handler: nested
                    excluded_http_codes: [404, 405]
                    buffer_size: 50  # Limite de messages tamponnés pour éviter les fuites de mémoire
                nested:
                    type: stream
                    path: php://stderr  # Utiliser stderr pour les logs en production
                    level: error  # Enregistrer les erreurs critiques seulement
                    formatter: monolog.formatter.json  # Format JSON pour la production
                console:
                    type: console
                    process_psr_3_messages: false
                    channels: ["!event", "!doctrine"]  # Exclure les canaux 'event' et 'doctrine'
                deprecation:
                    type: stream
                    path: php://stderr  # Utiliser stderr pour les dépréciations
                    level: notice  # Niveau de log pour les dépréciations
                    channels: [deprecation]  # Canal dédié aux dépréciations
