imports:
        - { resource: ../nelmio/login.yaml }
        - { resource: ../nelmio/phones.yaml }
        - { resource: ../nelmio/phone-id.yaml }
        - { resource: ../nelmio/users.yaml }
        - { resource: ../nelmio/user-id.yaml }
nelmio_api_doc:
    documentation:
        info:
            title: Bilmo API
            description:
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
        paths:
            '/api/phones': '%nelmio_phones%'
            '/api/phones/{id}': '%nelmio_phone_id%'
            '/api/login_check': '%nelmio_login%'
            '/api/users': '%nelmio_users%'
            '/api/users/{id}': '%nelmio_user_id%'
        tags:
            -
                name: authentication
                description: Authentication on this API
            -
                name: phone
                description: Phones proposed in catalog
            -
                name: user
                description: Users linked to customers

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
