@startuml

title Add User diagramme de séquence

participant CLIENT
participant APP
participant BDD

CLIENT -> APP: Requête POST "/api/users" JSON et envoie de token
activate APP
APP -> APP : Vérifie si le token et les données sont corrects

alt Si le token est valide
  APP -> APP : Deserialize data
  APP -> APP : Vérifie si tous les champs requis sont remplis

  alt Si tous les champs sont remplis
    APP -> BDD : Ajoute les données (users)
    activate BDD
    BDD --> APP: User créé
    deactivate BDD
    APP --> CLIENT : Confirmation enregistrement
  else Si un ou plusieurs champs sont manquants
    APP --> CLIENT : 400 Champs requis manquants
  end

else Si token non valide
    APP --> CLIENT : 401 (Utilisateur non authentifié)
end

alt Si données invalides
    APP --> CLIENT : 400 Données invalides
end

@enduml
