@startuml

title Get Phones diagramme de séquence

participant CLIENT
participant APP
participant BDD

CLIENT -> APP: Requête GET "/api/phones"
activate APP
APP -> BDD  : Requête find all pour récupérer toutes les données
activate BDD
BDD --> APP : Retour de la requête (liste des téléphones)
deactivate BDD
APP -> APP : Serialize DATA
APP --> CLIENT : 200 (Liste des téléphones)

@enduml
