@startuml

entity "Phone" {
  + id : string
  name : string
  content : text
  color : string
  storage : int
  price : float
  image : string
}

entity "User" {
  + id : string
    username : string
    email : string
    roles : array|json
    password : string
    createdAt : datetime
}

entity "Client" {
    + id : string
     user_id : string
     username : string
}

User "1" -- "0..*" Client

@enduml